name: 'Push to ECR'
description: 'push image to ECR targets'
inputs:
  local-image:
    description: 'local image (<name>:<tag>)'
    required: false
  remote-image:
    description: 'remote image (<accountId>.dkr.ecr.<region>.amazonaws.com/<name>:<tag>)'
    required: false
  extra-tags:
    description: 'pass values from the workflow to be used as tags'
    required: false
  ecr-repository:
    description: "ECR repository name"
    required: true
    type: string
  force-push: 
    description: "Boolean value if to force push tags at immutable repository"
    required: false
    default: false
    type: boolean
  registry-id: 
    description: "registry"
    required: false
    type: string
    default: CORP
runs:
  using: 'node12'
  main: 'index.js'