name: 'Push to ECR'
description: 'push image to ECR targets'
inputs:
  env-key:
    description: 'environemnt key'
    required: true
  local-image:
    description: 'local image (<name>:<tag>)'
    required: false
  remote-image:
    description: 'remote image (<accountId>.dkr.ecr.<region>.amazonaws.com/<name>:<tag>)'
    required: false
  app-version:
    description: 'version of the pushed image, made only from numbers and dots (ex. 1.2.6)'
    required: false
  extra-tags:
    description: 'pass values from the workflow to be used as tags'
    required: false
runs:
  using: 'node12'
  main: 'index.js'